### ISSUE TITLE
Remove Htts from the Pop sample?

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#156]
See @hpsin

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hpsin** [comment]
Confusion on my end on this front: 
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#http-strict-transport-security-protocol-hsts

I was thinking this was HSTS on the application calling APIs, but it's the app talking to the browser.  I don't have a strong opinion there, IMO HSTS is a great way to kill your app's reliability, but it's up to the dev. We don't recommend that you cache/pin the certs for Graph/login.mso.com etc, since we don't use HSTS.  I was concerned this was somehow doing that pinning.

Can close, no action needed.

**Comment by jmprieur** [comment]
Thanks for digging into it, @hpsin 
Closing it, then.
