### ISSUE TITLE
Should check tenantId and not jwtToken again

### ISSUE THREAD

**Issue by goofybryan** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#18]
A check the jwtToken == null is done again, instead of tenantId == null or string.IsNullOrEmpty perhaps?

```c#
// Extracting the tenant ID
string tenantId = jwtToken.Claims.FirstOrDefault(c => c.Type == "tid")?.Value;
if (jwtToken == null)  // Should be if (string.IsNullOrEmpty(tentantId)) or if (tenantId == null)
{
    throw new SecurityTokenInvalidIssuerException("Expecting a tid claim from Azure Active Directory.");
}
```
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/500fc267b5a9decb8ea96fe8b8084aea886c6350/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/Extensions/AadIssuerValidator.cs#L32

**Comment by jmprieur** [comment]
Thanks @goofybryan !

This is now fixed in this sample, 

I've raised a similar issue to fix it in https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2: See [#26](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/26)

cc: @kalyankrishna1
